[package]
name = "glyph_brush"
version = "0.2.4"
authors = ["Alex Butler <alexheretic@gmail.com>"]
edition = "2018"
description = "Fast cached text render library using rusttype"
repository = "https://github.com/alexheretic/gfx-glyph"
keywords = ["font", "ttf", "truetype", "text"]
license = "Apache-2.0"
readme="README.md"

[dependencies]
glyph_brush_layout = { version = "0.1.1", path = "../glyph-brush-layout" }
log = "0.4.4"
ordered-float = "1"
full_rusttype = { version = "0.7", features = ["gpu_cache"], package = "rusttype" }
seahash = "3"
hashbrown = "0.1"
thread_profiler = { version = "0.3", features = ["thread_profiler"] }

[dev-dependencies]
env_logger = { version = "0.6", default-features = false }
lazy_static = "1"
gl = "0.11"
glutin = "0.19"
spin_sleep = "0.3"

[features]
profiler = [ "thread_profiler/thread_profiler" ]